# Generated by Django 6.0.4 on 2026-04-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='functions.route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='functions.route'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distance',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_distances', to='functions.city'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_distances', to='functions.city'),
        ),
        migrations.AlterField(
            model_name='topvisitors',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.city'),
        ),
        migrations.AlterField(
            model_name='transportdetail',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_from', to='functions.city'),
        ),
        migrations.AlterField(
            model_name='transportdetail',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_to', to='functions.city'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='yearly',
            field=models.BigIntegerField(),
        ),
    ]
